# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0022_auto_20170806_1613'),
        ('collection', '0004_auto_20170812_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ManyToManyField(to='produit.Produit')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='produit',
            field=models.ManyToManyField(null=True, to='produit.Produit'),
        ),
    ]
