# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20170812_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='produit',
            field=models.ManyToManyField(to='produit.Produit'),
        ),
    ]
