# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0022_auto_20170806_1613'),
        ('collection', '0006_auto_20170812_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='produit',
        ),
        migrations.AddField(
            model_name='test',
            name='produits',
            field=models.ManyToManyField(blank=True, null=True, to='produit.Produit'),
        ),
    ]
