# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20170814_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='produit',
            field=models.ManyToManyField(blank=True, null=True, to='produit.Produit'),
        ),
    ]
