# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20170814_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='produits',
        ),
        migrations.AlterField(
            model_name='collection',
            name='produit',
            field=models.ManyToManyField(blank=True, to='produit.Produit'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
