# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 20:28
from __future__ import unicode_literals

import album.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to=album.models.group_based_upload_to_seconder),
        ),
        migrations.AlterField(
            model_name='picture',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='album.Album'),
        ),
    ]
