# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170822_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
    ]
