# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_picture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
