# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0022_auto_20170806_1613'),
        ('collection', '0008_auto_20170814_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('flashe', 'flashe'), ('regular', 'regular')], default='vintage', max_length=250)),
                ('types', models.CharField(max_length=1, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Collection')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.Produit')),
            ],
        ),
    ]
