# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotion_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
