# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20170816_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='timeend',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='timestart',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
