# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_auto_20170820_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
