# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_auto_20170821_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='type',
            new_name='promo_type',
        ),
    ]
