# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.FileField(max_length=250, upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image2', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image3', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(default=None, max_length=250)),
                ('etat', models.CharField(choices=[('active', 'active'), ('desactive', 'desactive')], default='desactive', max_length=250)),
                ('descreption', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to=produit.models.group_based_upload_to)),
                ('image1', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image2', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image3', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('categorie', models.CharField(choices=[('bijoux ', 'bijoux '), ('maison et ameublement', 'maison et ameublement'), ('vetements ', 'vetements '), ('art et collections', 'art et collections'), ('accessoires ', 'accessoires '), ('sacs et bagages', 'sacs et bagages'), ('mariage ', 'mariage ')], default='bijoux', max_length=250)),
                ('dat', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantite', models.IntegerField(default=None)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.Boutique')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=250)),
                ('description', models.CharField(default=None, max_length=250)),
                ('Picture', models.FileField(max_length=250, upload_to='')),
                ('Type', models.CharField(choices=[('Entreprise', 'Entreprise'), ('Particulier', 'Particulier')], default='Entreprise', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
