# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('vintage', 'vintage'), ('fait a la main', 'fait a la main')], default='vintage', max_length=250),
        ),
    ]
