# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_auto_20170711_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image1',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image3',
            field=models.ImageField(default=None, upload_to=produit.models.group_based_upload_to),
        ),
    ]
