# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0006_produit_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='likers',
        ),
        migrations.AddField(
            model_name='produit',
            name='likers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
