# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0007_auto_20170722_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='likers',
        ),
        migrations.AddField(
            model_name='produit',
            name='likers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
