# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0008_auto_20170722_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='likers',
        ),
        migrations.AddField(
            model_name='produit',
            name='likers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
