# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_auto_20170723_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='likers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
