# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0012_auto_20170723_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
