# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0013_auto_20170723_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
