# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0015_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='Type',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='type',
            field=models.CharField(choices=[('ENTERPRISE', 'Entreprise'), ('INDIVIDUAL', 'Particulier')], max_length=255, null=True),
        ),
    ]
