# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0016_auto_20170724_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='Username',
            new_name='username',
        ),
    ]
