# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0018_auto_20170724_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'normal'), ('SMILE', 'smile'), ('LOVE', 'love'), ('WISH', 'wish')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'produit')]),
        ),
    ]
