# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0020_auto_20170801_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
