# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0021_auto_20170802_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
