# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
